### ISSUE TITLE
Eliminação de recursão à esquerda

### ISSUE THREAD

**Issue by mvrozanti** [FernandoBontorin/altpascal-compiler#3]
Eyy Fernando

Já fez essa parte?

Pra quando é sua entrega? 

Tá fazendo com o Bob também?

Como remover recursão (direta ou indireta) à esquerda? 

Acho que achei uma:

```
<comando_composto> ::= begin <comando> { ; <comando> } end

<comando> ::= ... | ... | <comando_composto> | ...
```

Abraços autômatos

**Comment by FernandoBontorin** [comment]
Não fiz ainda

Em breve kk

sim, estou

vou chegar lá, espero

Abraços texugo

**Comment by mvrozanti** [comment]
Sei lá se isso que eu falei era recursão à esquerda

Não precisei fatorar nem eliminar nada

Case closed
